<div class="table_container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Month</th>
                <th>Total Numbers</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>January</td>
                <td>{{$JanCount16}}</td>
            </tr>
            <tr>
                <td>February</td>
                <td>{{$FebCount16}}</td>
            </tr>
            <tr>
                <td>March</td>
                <td>{{$MarCount16}}</td>
            </tr>
            <tr>
                <td>April</td>
                <td>{{$AprCount16}}</td>
            </tr>
            <tr>
                <td>May</td>
                <td>{{$MayCount16}}</td>
            </tr>
            <tr>
                <td>June</td>
                <td>{{$JuneCount16}}</td>
            </tr>
            <tr>
                <td>July</td>
                <td>{{$JulyCount16}}</td>
            </tr>
            <tr>
                <td>August</td>
                <td>{{$AugCount16}}</td>
            </tr>
            <tr>
                <td>September</td>
                <td>{{$SeptCount16}}</td>
            </tr>
            <tr>
                <td>October</td>
                <td>{{$OctCount16}}</td>
            </tr>
            <tr>
                <td>November</td>
                <td>{{$NovCount16}}</td>
            </tr>
            <tr>
                <td>December</td>
                <td>{{$DecCount16}}</td>
            </tr>
        </tbody>
    </table>
</div>
