<div class="table_container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Month</th>
                <th>Total Numbers</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>January</td>
                <td>{{$JanCount15}}</td>
            </tr>
            <tr>
                <td>February</td>
                <td>{{$FebCount15}}</td>
            </tr>
            <tr>
                <td>March</td>
                <td>{{$MarCount15}}</td>
            </tr>
            <tr>
                <td>April</td>
                <td>{{$AprCount15}}</td>
            </tr>
            <tr>
                <td>May</td>
                <td>{{$MayCount15}}</td>
            </tr>
            <tr>
                <td>June</td>
                <td>{{$JuneCount15}}</td>
            </tr>
            <tr>
                <td>July</td>
                <td>{{$JulyCount15}}</td>
            </tr>
            <tr>
                <td>August</td>
                <td>{{$AugCount15}}</td>
            </tr>
            <tr>
                <td>September</td>
                <td>{{$SeptCount15}}</td>
            </tr>
            <tr>
                <td>October</td>
                <td>{{$OctCount15}}</td>
            </tr>
            <tr>
                <td>November</td>
                <td>{{$NovCount15}}</td>
            </tr>
            <tr>
                <td>December</td>
                <td>{{$DecCount15}}</td>
            </tr>
        </tbody>
    </table>
</div>
